// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElAside: typeof import('element-plus/es')['ElAside']
		ElAvatar: typeof import('element-plus/es')['ElAvatar']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElDrawer: typeof import('element-plus/es')['ElDrawer']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElHeader: typeof import('element-plus/es')['ElHeader']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElMain: typeof import('element-plus/es')['ElMain']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElSwitch: typeof import('element-plus/es')['ElSwitch']
		ElTable: typeof import('element-plus/es')['ElTable']
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		UsePinia: typeof import('./components/UsePinia.vue')['default']
	}
}
